#Your Destination folder may look very different, on windows. the proper mod folder location for install is in /My Documents/My Games/FarmingSimulator2019/mods
#This mod was made on a linux distro using SteamPlay and ProtonDB, so the install path is abstracted and hidden deep within the belly of steam compatdata
DEST='/home/idrious/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/787860/pfx/drive_c/users/steamuser/My Documents/My Games/FarmingSimulator2019/mods'

default:
	zip -r XRFS19Mod.zip * -x *.zip
	cp XRFS19Mod.zip $(DEST)/