DEST='/home/idrious/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/787860/pfx/drive_c/users/steamuser/My Documents/My Games/FarmingSimulator2019/mods'

default:
	zip test.zip modDesc.xml *.lua
	cp test.zip $(DEST)/

