DEST=/home/conrad/.local/share/Steam/steamapps/compatdata/787860/pfx/drive_c/users/steamuser/My\ Documents/My\ Games/FarmingSimulator2019/mods

default:
	cd test
	zip test.zip modDesc.xml test.lua
	cp test.zip $(DEST)/
